outputs = "All"

[modules]
left = ["WindowTitle"]
center = ["MediaPlayer", ["Workspaces", "Clock"]]
right = [["SystemInfo", "Tray"], "Settings"]

[window_title]
mode = "Title"
truncate_title_after_length = 40

[media_player]
max_title_length = 30

[appearance]
opacity = 0.8
style = "Solid"
success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
[appearance.menu]
opacity = 0.9
